### ISSUE TITLE
npm run export

### ISSUE THREAD

**Issue by steven001** [salomonelli/best-resume-ever#110]
### Case

- HELP QUESTION

## Issue

Running the export command, many errors are reported.
`Starting dev server...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1344:14)
    at listenInCluster (net.js:1385:12)
    at Server.listen (net.js:1469:7)
    at Function.listen ( /Users/....../best-resume-ever-master/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/......./best-resume-ever-master/build/dev-server.js:87:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

## Info
- Operating System: OSX Sierra 10.12.6
- Node-Version: 8.7.0

## Reproduce

run `npm run export`

**Comment by mbndr** [comment]
If the problem is not solved already:
`Error: listen EADDRINUSE :::8080` means that port 8080 is already used by another application.

**Comment by steven001** [comment]
thanks,solved already

**Comment by youngjuning** [comment]
![2017-11-18_152023](https://user-images.githubusercontent.com/13204332/32978157-6267e6e0-cc77-11e7-9cc7-3803ff9acf91.png)
