### ISSUE TITLE
Cannot run 'npm run dev' on Linux

### ISSUE THREAD

**Issue by GabrielCoelho** [salomonelli/best-resume-ever#131]
### Case
- BUG

## Issue
Trying to execute `npm run dev` and getting an error message. Tried to clone from the original repository and I'm getting the same error. 

## Info
- Operating System: Linux (Ubuntu 16.04.3)
- Node-Version: 8.9.0
## Reproduce
~~~bash
0 info it worked if it ends with ok
1 verbose cli [ '/home/gabrielcs/.nvm/versions/node/v8.9.0/bin/node',
1 verbose cli   '/home/gabrielcs/.nvm/versions/node/v8.9.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle best-resume-ever@1.0.0~predev: best-resume-ever@1.0.0
6 verbose lifecycle best-resume-ever@1.0.0~predev: unsafe-perm in lifecycle true
7 verbose lifecycle best-resume-ever@1.0.0~predev: PATH: /home/gabrielcs/.nvm/versions/node/v8.9.0/lib/node_modules/npm/bin/node-gyp-bin:/home/gabrielcs/Documentos/WebSites/awesome-cv-creator/node_modules/.bin:/home/gabrielcs/.nvm/versions/node/v8.9.0/bin:/home/gabrielcs/bin:/home/gabrielcs/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
8 verbose lifecycle best-resume-ever@1.0.0~predev: CWD: /home/gabrielcs/Documentos/WebSites/awesome-cv-creator
9 silly lifecycle best-resume-ever@1.0.0~predev: Args: [ '-c', 'check-node-version --node ">= 8.0.0"' ]
10 silly lifecycle best-resume-ever@1.0.0~predev: Returned: code: 1  signal: null
11 info lifecycle best-resume-ever@1.0.0~predev: Failed to exec predev script
12 verbose stack Error: best-resume-ever@1.0.0 predev: `check-node-version --node ">= 8.0.0"`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/home/gabrielcs/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at EventEmitter.emit (events.js:214:7)
12 verbose stack     at ChildProcess.<anonymous> (/home/gabrielcs/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid best-resume-ever@1.0.0
14 verbose cwd /home/gabrielcs/Documentos/WebSites/awesome-cv-creator/resume
15 verbose Linux 4.10.0-38-generic
16 verbose argv "/home/gabrielcs/.nvm/versions/node/v8.9.0/bin/node" "/home/gabrielcs/.nvm/versions/node/v8.9.0/bin/npm" "run" "dev"
17 verbose node v8.9.0
18 verbose npm  v5.5.1
19 error code ELIFECYCLE
20 error errno 1
21 error best-resume-ever@1.0.0 predev: `check-node-version --node ">= 8.0.0"`
21 error Exit status 1
22 error Failed at the best-resume-ever@1.0.0 predev script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
~~~

**Comment by pubkey** [comment]
`check-node-version --node ">= 8.0.0"` fails which indicates your node-version is too low. Are you sur that you have node version 8.9.0 and installed all dependencies?

**Comment by GabrielCoelho** [comment]
I'm sure. My node Version is 8.9.0. 
Doing all the steps on README file and still getting the same error.

**Comment by GabrielCoelho** [comment]
Almost two weeks later and still getting the same error. 
Even with the latest commits. :cry:

**Comment by nesar11** [comment]
broken@broken-HP-Compaq-dc7800-Small-Form-Factor:~$ npm run dev
npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/home/broken/.nvm/versions/node/v6.0.0/bin/node" "/home/broken/.nvm/versions/node/v6.0.0/bin/npm" "run" "dev"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! path /home/broken/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/broken/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/broken/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/broken/npm-debug.log

**Comment by nesar11** [comment]
How to fixed this

**Comment by pubkey** [comment]
Closing this.
@nesar11 I'm sorry but your description does not help.
@GabrielCoelho  I don't think there is a chance that I can reproduce this.
