### ISSUE TITLE
npm run export | Unexpected token ( 

### ISSUE THREAD

**Issue by muhtarudinsiregar** [salomonelli/best-resume-ever#15]
I get error when `npm run export` after clone  repo.

**Specification**
```
>node -v
V6.11.2`

>npm -v
4.6.1

```
**How to reproduce ?**
* clone repo
* run `npm install`
* run `npm run export`

```
> $ npm run export

> best-resume-ever@1.0.0 pdf D:\Development\Latihan\best-resume-ever
> node node/app.js

D:\Development\Latihan\best-resume-ever\node\app.js:22
    .mergeMap(async() => {
                    ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 pdf: `node node/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-resume-ever@1.0.0 pdf script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MY ASUS\AppData\Roaming\npm-cache\_logs\2017-09-11T13_09_39_150Z-debug.log
```

**Comment by pubkey** [comment]
You need a node-version that supports async/await. Please update to v7 or higher.
