### ISSUE TITLE
`npm run export` does not work

### ISSUE THREAD

**Issue by jhnferraris** [salomonelli/best-resume-ever#16]
I followed the instructions in the README.md. When I tried executing `$ npm run export`, it fails

```
jhn-work% npm run export

> best-resume-ever@1.0.0 export /Users/jhnferraris/Projects/Sides/best-resume-ever
> concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw


> best-resume-ever@1.0.0 dev /Users/jhnferraris/Projects/Sides/best-resume-ever
> node build/dev-server.js


> best-resume-ever@1.0.0 pdf /Users/jhnferraris/Projects/Sides/best-resume-ever
> node node/app.js

/Users/jhnferraris/Projects/Sides/best-resume-ever/node/app.js:22
    .mergeMap(async() => {
                   ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "pdf"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! best-resume-ever@1.0.0 pdf: `node node/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-resume-ever@1.0.0 pdf script 'node node/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jhnferraris/Projects/Sides/best-resume-ever/npm-debug.log

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "export"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! best-resume-ever@1.0.0 export: `concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-resume-ever@1.0.0 export script 'concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jhnferraris/Projects/Sides/best-resume-ever/npm-debug.log
```

Steps:

1. Run npm install.
2. Edit your personal data in src/person.js. 
3. Preview resumes with npm run dev.
4. Export with npm run export.

**Comment by derickfelix** [comment]
Did you try installing the latest version?

**Comment by jhnferraris** [comment]
@derickfelix I'm in the `master` branch. Which branch should I use?

**Comment by jhnferraris** [comment]
Oh I'm sorry. You're referring to the node version. 
I'm on 7.4.

What's the minimum version for this application, anyway?

**Comment by derickfelix** [comment]
I am not sure, but I am using the v8.4.0 and it's working normally

**Comment by jhnferraris** [comment]
Thanks! It requires higher than 7.4. Version 8.4.0 fixed it.
