### ISSUE TITLE
Unable to install by mentioned steps

### ISSUE THREAD

**Issue by garunaX** [salomonelli/best-resume-ever#187]
### Help
On running the mentioned steps the program is exiting with an error

## Issue / log of error

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/home/garuna/.nvm/versions/node/v8.9.1/bin/node',
1 verbose cli   '/home/garuna/.nvm/versions/node/v8.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle best-resume-ever@1.0.0~predev: best-resume-ever@1.0.0
6 verbose lifecycle best-resume-ever@1.0.0~predev: unsafe-perm in lifecycle true
7 verbose lifecycle best-resume-ever@1.0.0~predev: PATH: /home/garuna/.nvm/versions/node/v8.9.1/lib/node_modules/npm/bin/node-gyp-bin:/home/garuna/Desktop/work/best-resume-ever/node_modules/.bin:/home/garuna/.nvm/versions/node/v8.9.1/bin:/home/garuna/.rbenv/bin:/home/garuna/bin:/home/garuna/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/garuna/.rvm/bin:/bin:/util/flexlm/x86_64_re3:/home/garuna/.rvm/bin
8 verbose lifecycle best-resume-ever@1.0.0~predev: CWD: /home/garuna/Desktop/work/best-resume-ever
9 silly lifecycle best-resume-ever@1.0.0~predev: Args: [ '-c', 'check-node-version --node ">= 8.0.0"' ]
10 silly lifecycle best-resume-ever@1.0.0~predev: Returned: code: 0  signal: null
11 info lifecycle best-resume-ever@1.0.0~dev: best-resume-ever@1.0.0
12 verbose lifecycle best-resume-ever@1.0.0~dev: unsafe-perm in lifecycle true
13 verbose lifecycle best-resume-ever@1.0.0~dev: PATH: /home/garuna/.nvm/versions/node/v8.9.1/lib/node_modules/npm/bin/node-gyp-bin:/home/garuna/Desktop/work/best-resume-ever/node_modules/.bin:/home/garuna/.nvm/versions/node/v8.9.1/bin:/home/garuna/.rbenv/bin:/home/garuna/bin:/home/garuna/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/garuna/.rvm/bin:/bin:/util/flexlm/x86_64_re3:/home/garuna/.rvm/bin
14 verbose lifecycle best-resume-ever@1.0.0~dev: CWD: /home/garuna/Desktop/work/best-resume-ever
15 silly lifecycle best-resume-ever@1.0.0~dev: Args: [ '-c', 'node build/dev-server.js' ]
16 silly lifecycle best-resume-ever@1.0.0~dev: Returned: code: 1  signal: null
17 info lifecycle best-resume-ever@1.0.0~dev: Failed to exec dev script
18 verbose stack Error: best-resume-ever@1.0.0 dev: `node build/dev-server.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/home/garuna/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at EventEmitter.emit (events.js:214:7)
18 verbose stack     at ChildProcess.<anonymous> (/home/garuna/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:925:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose pkgid best-resume-ever@1.0.0
20 verbose cwd /home/garuna/Desktop/work/best-resume-ever
21 verbose Linux 4.4.0-101-generic
22 verbose argv "/home/garuna/.nvm/versions/node/v8.9.1/bin/node" "/home/garuna/.nvm/versions/node/v8.9.1/bin/npm" "run" "dev"
23 verbose node v8.9.1
24 verbose npm  v5.5.1
25 error code ELIFECYCLE
26 error errno 1
27 error best-resume-ever@1.0.0 dev: `node build/dev-server.js`
27 error Exit status 1
28 error Failed at the best-resume-ever@1.0.0 dev script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

## Info
- Operating System: 
- Node-Version: 

## Reproduce
just run the steps mentioned in readme with current version

## system specification
ubuntu:	16.04

**Comment by pubkey** [comment]
Can you do `node -v` and `nodejs -v` ? I think you are missing a symlink.

**Comment by garunaX** [comment]
Both are of  v8.9.1.

**Comment by GabrielCoelho** [comment]
For me, I was only able to make it functional after removing the `predev` script (in package.json). Even updating as in #188 did not work (and look that I've been trying since November 2 #131)

**Comment by pubkey** [comment]
Thx @GabrielCoelho  that helps.
@garunaX can you do:

```bash
npm i -g check-node-version
check-node-version --node \">= 8.0.0\"
```

**Comment by pubkey** [comment]
Closed because of no response.
