### ISSUE TITLE
npm run export not working  I had issues on npm install too

### ISSUE THREAD

**Issue by vip20** [salomonelli/best-resume-ever#26]
### Case

I had issues on both "npm install" as well as "npm run export"

**Below one is for npm install**

```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "E:\\Software\\node.js\\node.exe" "C:\\Users\\%USER%\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\resume builder\best-resume-ever-master\npm-debug.log

```

**Below one for "npm run export"**

```
F:\resume builder\best-resume-ever-master\node\app.js:22
    .mergeMap(async() => {
                   ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "E:\\Software\\node.js\\node.exe" "C:\\Users\\Vinay\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "pdf"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! best-resume-ever@1.0.0 pdf: `node node/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-resume-ever@1.0.0 pdf script 'node node/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\resume builder\best-resume-ever-master\npm-debug.log

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "E:\\Software\\node.js\\node.exe" "C:\\Users\\%USER%\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "export"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! best-resume-ever@1.0.0 export: `concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-resume-ever@1.0.0 export script 'concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\resume builder\best-resume-ever-master\npm-debug.log
```

## Info
- Operating System: Windows
- Node-Version: 6.11.3

**Comment by salomonelli** [comment]
Please upgrade your node version to the latest. If the error still occurs please refer to #24. We might have problems with windows.

**Comment by Wintershadow1** [comment]
npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! best-resume-ever@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dell/best-resume-ever/npm-debug.log
root@dell-Vostro-1520:/home/dell/best-resume-ever#

**Comment by Wintershadow1** [comment]
Node-Version 8.10
Linux 19.2
