### ISSUE TITLE
can't export in pdf

### ISSUE THREAD

**Issue by boblinux** [salomonelli/best-resume-ever#33]
### Case
- BUG
## Issue
Can't export my resume in pdf

## Info
- Operating System: WINDOWS 10
- npm version : 3.10.10
- Node-Version : v6.11.3

## Reproduce
when i do : npm run export, i get an error, here is my npm-debug.log file : 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'export' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'preexport', 'export', 'postexport' ]
5 info lifecycle best-resume-ever@1.0.0~preexport: best-resume-ever@1.0.0
6 silly lifecycle best-resume-ever@1.0.0~preexport: no script for preexport, continuing
7 info lifecycle best-resume-ever@1.0.0~export: best-resume-ever@1.0.0
8 verbose lifecycle best-resume-ever@1.0.0~export: unsafe-perm in lifecycle true
9 verbose lifecycle best-resume-ever@1.0.0~export: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\azzed\Downloads\softs\best-resume-ever-master\best-resume-ever-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\azzed\AppData\Local\Microsoft\WindowsApps;C:\Users\azzed\AppData\Roaming\npm
10 verbose lifecycle best-resume-ever@1.0.0~export: CWD: C:\Users\azzed\Downloads\softs\best-resume-ever-master\best-resume-ever-master
11 silly lifecycle best-resume-ever@1.0.0~export: Args: [ '/d /s /c',
11 silly lifecycle   'concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw' ]
12 silly lifecycle best-resume-ever@1.0.0~export: Returned: code: 1  signal: null
13 info lifecycle best-resume-ever@1.0.0~export: Failed to exec export script
14 verbose stack Error: best-resume-ever@1.0.0 export: `concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid best-resume-ever@1.0.0
16 verbose cwd C:\Users\azzed\Downloads\softs\best-resume-ever-master\best-resume-ever-master
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "export"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error best-resume-ever@1.0.0 export: `concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw`
22 error Exit status 1
23 error Failed at the best-resume-ever@1.0.0 export script 'concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the best-resume-ever package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs best-resume-ever
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls best-resume-ever
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by alessandrostone** [comment]
I think you need higher node version, like 7

**Comment by nacimgoura** [comment]
Yes, it has already said several times. you need minimum nodejs 7.4.

**Comment by salomonelli** [comment]
Please upgrade node. If you still have problems please refer to #24 .
