### ISSUE TITLE
Fail to export to PDF

### ISSUE THREAD

**Issue by atZERO** [salomonelli/best-resume-ever#36]
### Case
- BUG

## Issue
Fail to export to PDF

## Info
- Operating System: OSX 
- Node-Version: node -v' 7.5.0

## Log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'export' ]
2 info using npm@5.4.1
3 info using node@v7.5.0
4 verbose run-script [ 'preexport', 'export', 'postexport' ]
5 info lifecycle best-resume-ever@1.0.0~preexport: best-resume-ever@1.0.0
6 info lifecycle best-resume-ever@1.0.0~export: best-resume-ever@1.0.0
7 verbose lifecycle best-resume-ever@1.0.0~export: unsafe-perm in lifecycle true
8 verbose lifecycle best-resume-ever@1.0.0~export: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/nrahal/Code/best-resume-ever/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle best-resume-ever@1.0.0~export: CWD: /Users/nrahal/Code/best-resume-ever
10 silly lifecycle best-resume-ever@1.0.0~export: Args: [ '-c',
10 silly lifecycle   'concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw' ]
11 silly lifecycle best-resume-ever@1.0.0~export: Returned: code: 1  signal: null
12 info lifecycle best-resume-ever@1.0.0~export: Failed to exec export script
13 verbose stack Error: best-resume-ever@1.0.0 export: `concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:192:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:192:7)
13 verbose stack     at maybeClose (internal/child_process.js:890:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid best-resume-ever@1.0.0
15 verbose cwd /Users/nrahal/Code/best-resume-ever
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "export"
18 verbose node v7.5.0
19 verbose npm  v5.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error best-resume-ever@1.0.0 export: `concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw`
22 error Exit status 1
23 error Failed at the best-resume-ever@1.0.0 export script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by nacimgoura** [comment]
Hello,
delete the node_modules folder, move the project to another directory and try again from the beginning.
Tell me if it works :smiley:

**Comment by salomonelli** [comment]
Please try a newer node version and tell us if it works.

**Comment by atZERO** [comment]
**Nope**

> best-resume-ever@1.0.0 dev /Code/best-resume-ever
> node build/dev-server.js

> Starting dev server...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1343:14)
    at listenInCluster (net.js:1391:12)
    at Server.listen (net.js:1474:7)

etc...

**Comment by mbndr** [comment]
`EADDRINUSE :::8080` means that another program is using the port I think. Same problem in a previous issue.

**Comment by pubkey** [comment]
I think this is solved.
As @mbndr said, make sure your node-version is equal or higher than the readme recommends.
And make sure port 8080 is not used by another programm.
