### ISSUE TITLE
Error: Cannot find module 'webpack/lib/RuleSet'

### ISSUE THREAD

**Issue by krittin-58** [salomonelli/best-resume-ever#388]
### Case
Cannot npm run dev

## Issue
I cannot run command "npm run dev" following your topic => How to use? at README.md

## Info
- Operating System: `OSX`
- Node-Version: `12.16.3`

## Reproduce
1. Clone this repository. => `git clone https://github.com/salomonelli/best-resume-ever.git`
2. Go to the cloned directory (e.g. `cd best-resume-ever`).
3. Run `npm install`
4. Run `npm run dev`
5. Found issue messages (below)

Error: Cannot find module 'webpack/lib/RuleSet'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/xxxxx/Desktop/PROJECTS/vue/best-resume-ever/node_modules/vue-loader/lib/plugin.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2021-01-28T04_12_15_257Z-debug.log

**Comment by prashantswami** [comment]
I could able to run this, without any error. @krittin-58 could you please try again may be deleting `node_modules` and again running `npm i`.
