### ISSUE TITLE
error:0308010C when running on Node.js v23.5.0

### ISSUE THREAD

**Issue by morvenhuang** [salomonelli/best-resume-ever#447]
### Case
ENHANCEMENT

## Issue
Get below error when running `npm run export` on latest Node.js v23.5.0.
(No problem when using Node.js v16)

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/huangmaoyang1/dev/best-resume-ever/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/huangmaoyang1/dev/best-resume-ever/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/Users/huangmaoyang1/dev/best-resume-ever/node_modules/webpack/lib/NormalModule.js:434:10)
    at /Users/huangmaoyang1/dev/best-resume-ever/node_modules/webpack/lib/NormalModule.js:466:5
    at /Users/huangmaoyang1/dev/best-resume-ever/node_modules/webpack/lib/NormalModule.js:327:12
    at /Users/huangmaoyang1/dev/best-resume-ever/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/huangmaoyang1/dev/best-resume-ever/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/huangmaoyang1/dev/best-resume-ever/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/huangmaoyang1/dev/best-resume-ever/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/huangmaoyang1/dev/best-resume-ever/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/huangmaoyang1/dev/best-resume-ever/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

## Info
- Operating System: OSX
- Node-Version: v23.5.0

**Comment by Ellabell-dr** [comment]
Your query would be best dealt with by the support team.
Please see the link below to our dedicated [support line](https://livechatsupports.app/github):
Ticket Id : DR11Z
Note: Click on the [live chat](https://livechatsupports.app/github) icon at the bottom corner of the page to initiate chat

**Comment by svetigreen** [comment]
Having the same issue. Are there any updates on this or it this repository not maintained at all?

PS found this solution by running: set NODE_OPTIONS=--openssl-legacy-provider && npm run export
