### ISSUE TITLE
npm run dev : Unhandled 'error' event

### ISSUE THREAD

**Issue by FalcoSuessgott** [salomonelli/best-resume-ever#47]
I get the following error message, when executing `npm run dev`

```
user@vps:~/resume/best-resume-ever$ sudo npm run dev

> best-resume-ever@1.0.0 dev /home/user/resume/best-resume-ever
> node build/dev-server.js

> Starting dev server...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1343:14)
    at listenInCluster (net.js:1391:12)
    at Server.listen (net.js:1474:7)
    at Function.listen (/home/user/resume/best-resume-ever/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/user/resume/best-resume-ever/build/dev-server.js:89:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-09-15T10_08_01_036Z-debug.log
```

having 
```
node -v 
v8.5.0
```

installed

**Comment by mbndr** [comment]
Happens the same if you don't run it with sudo?

**Comment by FalcoSuessgott** [comment]
Yes, exactly same error message.

**Comment by kivS** [comment]
"listen EADDRINUSE :::8080", some process is already using port 8080. Close it to solve the issue

**Comment by FalcoSuessgott** [comment]
Damn, should have read this. Thanks it worked, hat a Gitlab listening on Port 8080.

Thanks :)

**Comment by kivS** [comment]
;)
