### ISSUE TITLE
Does not run in Windows

### ISSUE THREAD

**Issue by mgrigajtis** [salomonelli/best-resume-ever#48]
### Case
Bug

## Issue
Unable to run in Windows 7

## Info
- Operating System: Windows 7
- Node-Version: 6.11.3
- NPM Version: 3.10.10

## Log file output:

```bash
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle best-resume-ever@1.0.0~predev: best-resume-ever@1.0.0
6 silly lifecycle best-resume-ever@1.0.0~predev: no script for predev, continuing
7 info lifecycle best-resume-ever@1.0.0~dev: best-resume-ever@1.0.0
8 verbose lifecycle best-resume-ever@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle best-resume-ever@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\ma331192\src\best-resume-ever\node_modules\.bin;%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Java\bin;C:\apache-maven-3.3.9\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files\nodejs\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Users\ma331192\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\ma331192\AppData\Local\Programs\Git\cmd;C:\Users\ma331192\AppData\Local\atom\bin
10 verbose lifecycle best-resume-ever@1.0.0~dev: CWD: C:\Users\ma331192\src\best-resume-ever
11 silly lifecycle best-resume-ever@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle best-resume-ever@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle best-resume-ever@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: best-resume-ever@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid best-resume-ever@1.0.0
16 verbose cwd C:\Users\ma331192\src\best-resume-ever
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error best-resume-ever@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the best-resume-ever@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the best-resume-ever package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs best-resume-ever
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls best-resume-ever
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Reproduce
npm run dev

EDIT by @pubkey : Format bash-output.

**Comment by mbndr** [comment]
Try executing with node v7.6 as mentioned in the README.md

**Comment by mgrigajtis** [comment]
Installed Node 8.5.0, worked fine.

**Comment by mbndr** [comment]
great :)

**Comment by metalray7mr** [comment]
same issue, running on win 8 and node 8.5.0

**Comment by mbndr** [comment]
I got it running on win10 and node 8.5.0
What exactly is your error message?

**Comment by pubkey** [comment]
Closing this because the original issue is solved. @metalray7mr Please create a separate issue with your console.output.
